### ISSUE TITLE
Low default value for heap space 

### ISSUE THREAD

**Issue by wawrzek** [corda/corda#1012]
Default value of Corda heap space (200m) is a bit low for many of scenario I don't think really necessary for developers anyway. (How many node do you need to run one workstation/laptop?) 512m sounds more reasonable.

**Comment by mikehearn** [comment]
We set it to 200 because some people were trying to run nodes on Raspberry Pis, but also, 5 nodes == 1.5-2GB of RAM because Java heap space is not the total memory usage of the process. And 5 nodes during a complex dev scenario does seem plausible.

What we really need to do here is make sure people are aware of the limit. Like by forcing you to pick between --dev or --prod in the command line or config file.
