### ISSUE TITLE
Problem issuing cash in Bank of Corda demo

### ISSUE THREAD

**Issue by ckr3** [corda/corda#146]
In the attached screenshot, please see the inability to add an issuer. Thanks !

![pasted image at 2017_01_10 10_35 am](https://cloud.githubusercontent.com/assets/22982244/21854390/931e3d7c-d7e8-11e6-8f51-ab4d22c7fdc8.png)

**Comment by Clintonio** [comment]
@josecoll didn't one of your latest fixes solve this already?

**Comment by patrickkuo** [comment]
It is fixed in master.
However, I am not sure if the fix is correct... before the fix we gather Issuers from the Vault, the list is empty because "BankOfCorda" doesn't have any cash. Populating the drop down with all the issuer in the network might cause inconvenience to the user when the number of issuer grow.
I think a warning label stating "No cash in Vault" will be sufficient.

**Comment by josecoll** [comment]
YEs - this is fixed here:
https://github.com/corda/corda/commit/4d0fef4701069dc08fdc8ebf86b691ef1a41b535
https://github.com/corda/corda/commit/172be1301d381eabdc64f9c000ad868e4543218a

**Comment by patrickkuo** [comment]
Will close this issue as it appeared to be fixed already.
