### ISSUE TITLE
FR: provide a Vault Query trackOnlyNewBy (streaming updates only) extension method

### ISSUE THREAD

**Issue by josecoll** [corda/corda#2163]
For scenarios, where it is neither required nor meaningful to require an initial snapshot.

**Comment by josecoll** [comment]
Following discussion on Slack #design channel:
https://cordaledger.slack.com/messages/C3J04VC3V/

**Comment by joeldudleyr3** [comment]
See https://r3-cev.atlassian.net/browse/CORDA-1400.

**Comment by lankydan** [comment]
Is this change to return an `Observable` rather than a `DataFeed` object? 

If so is a `trackOnlyNewBy` needed and instead have a `trackBy` that returns just the `Observable` and remove the "new" part. By using a default criteria we inherit only `UNCONSUMED` states anyway. I can see the argument for `trackOnlyUsedBy` (`CONSUMED`) states only but not a `trackOnlyNewBy`, unless it is just to remove confusion. In this case, I can see its merit. 

You could then also argue that there should be all 3 versions: `trackOnlyNewBy`, `trackOnlyUsedBy` and `trackOnlyAllBy`.

**Comment by davidrapacchiale** [comment]
Issued is tracked in Jira. This can be now closed
