### ISSUE TITLE
Why Do I Need A Transaction To Get Cash Balances?

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#2787]
In order to get a cash balance I need to do 

    val balance = testBank.database.transaction { testBank.services.getCashBalance(USD) }

If I don't wrap the call in a transaction 

    val balance = testBank.services.getCashBalance(USD)

I get

    java.lang.IllegalStateException: No transaction in context.

As an client developer I shouldn't have to care that I need a transaction and have to be exposed to your internal implementations.

There should be a simple api to get the cash balance and you should create the necessary transaction within it instead of making me repeat boilerplate code everywhere making my code harder to read.

**Comment by joeldudleyr3** [comment]
@rick-r3 Hey Rick, would this be possible?

**Comment by joeldudleyr3** [comment]
@opticyclic Unfortunately, the `ServiceHub` doesn't have a reference to the database that backs it. So in the context of tests, you have to tell it which database to use using a database transaction.

**Comment by rick-r3** [comment]
Actually, for the testing framework, we could add a `withServices` helper so the above could become:

`val balance = testBank.withServices { getCashBalance(USD) }`

It's not perfect, but I think could cut down on the boilerplate and if people get into the habit of using it (and we recommend it in documentation etc) rather than just `testBank.services`, it could be a reasonable win.  We can even give a nicer error message recommending this path if the `services` is used the old way without a transaction.

How does that sound?

**Comment by mikehearn** [comment]
I'd rather we fix this by making the service APIs create their own db transactions. It's really not obvious to me why it works this way currently, and this issue crops up in a lot of different ways and contexts.

**Comment by mikehearn** [comment]
See CORDA-825 https://r3-cev.atlassian.net/browse/CORDA-825

**Comment by davidrapacchiale** [comment]
Fixed as per https://github.com/corda/corda/pull/5088 PR
