### ISSUE TITLE
clarify OSS strategy

### ISSUE THREAD

**Issue by remmeier** [corda/corda#2993]
we have here Corda as OSS community and R3 as company being the main driver of the project. It would be great to see a clear statement about the OSS strategy. From the website this is not entirely clear, e.g. "Available as open source software or as an enterprise platform" (https://www.r3.com/technology/). https://www.r3.com/ecosystem/ gives some more details for the membership program.

**Comment by gendal** [comment]
Hi! Your timing is perfect. I've just proposed an update to our contribution guidelines to help make this clearer.  It's currently in review.  It would be great it you were to take a look and let us know what you think.  Does it answer your questions? If not, please do feel free to point out where more clarity is needed or if you think I haven't got the balance right, etc, etc: https://github.com/corda/corda/pull/2969

**Comment by mikehearn** [comment]
Initial areas our commercial offering differs are:

* Performance
* Database backend support
* Firewall bridging/integration (you can run a separate "float" component in a DMZ in Enterprise)
* High availability

There may be other areas of differentiation later. Our enterprise version isn't generally available yet but we're working on it, and when that's launched we'll have formal marketing materials describing the differences in more detail.

I'll close this now because this is more of a discussion than a bug report.

**Comment by mikehearn** [comment]
But please do feel free to continue the conversation - all I intend by closing the bug is getting it off the triage radar, I'm not trying to shut down the discussion.
