### ISSUE TITLE
Node names that contain commas don't work

### ISSUE THREAD

**Issue by lankydan** [corda/corda#3267]
Using Corda V3.1

Writing a node node that contains a comma does not work since it is the delimiter character used by `X500Name`. Using a backslash "\\" didnt work, which was mentioned as a escape character in https://tools.ietf.org/html/rfc1779 (X500Name documentation refers to this rfc).

Using a backslash (double backslash) due to gradle using groovy led to a node including a backslash in its name.

```groovy
node {
        name "O=ABC\\, DEF,L=Berlin,C=DE"
        p2pPort 10050
        rpcSettings {
            address("localhost:10005")
            adminAddress("localhost:10505")
        }
}
```
Running `deployNodes` lead to a node named `ABC\` which isn't what is desired.

Changes in CordaX500Name before passing the `name` field to `X500Name` might work, but I'm only guessing here.

**Comment by joeldudleyr3** [comment]
This is a known limitation. However, I am not aware of a reason why it could not be lifted.

**Comment by mikehearn** [comment]
What sort of node names need commas in them? Are you thinking of company names that have commas?

Yes, we could implement escaping everywhere, but we've tried to be restrictive when it comes to "special" characters in X.500 names because identity is so critical and such a sensitive attack surface. We're still not as tight as we should be, but, note that some rules are up to the zone operator to enforce.

**Comment by mikehearn** [comment]
Reopening - we should at least document the limitations clearly and produce good error messages. And if there's a simple set of fixes, let's do that too.

X.500 is natively binary so it's probably only at the edges that commas become special.

**Comment by lolo8304** [comment]
I take this one @joeldudleyr3

**Comment by lolo8304** [comment]
on master. I have tested

String
`O=Sue\, Grabbit and Runn, L=VALID, C=CH
`
X500Principal
`O="Sue, Grabbit and Runn", L=VALID, C=CH
`
X500Name —> RDNs have 2 String representation
`RFC 1779 = "Sue, Grabbit and Runn"
`
`RFC 2253 = Sue\, Grabbit and Runn
`
in todays CordaC500Name we are using toString() instead of a standardised one based on RFC1779 as in X500Name from sun (internal library)

**Comment by joeldudleyr3** [comment]
@lolo8304 So are you saying that commas in Corda X500 names are allowed and work?

**Comment by joeldudleyr3** [comment]
@lolo8304 I'd suggest opening a PR so we can take a look at the changes, even if you're not sure they pass the tests for now. This will also get TeamCity to run the tests for you.

**Comment by lolo8304** [comment]
pushed and created pull-request - see https://github.com/corda/corda/pull/4539
