### ISSUE TITLE
Include custom serialisers for java.util.Optional and java.math.BigInteger into Corda

### ISSUE THREAD

**Issue by ivanr3** [corda/corda#3531]
Corda doesn't include custom serialisers for java.util.Optional and java.math.BigInteger. This causes any serialisation attempt fail by default, if no custom serialisers have been provided by developers. Including serialisers for these popular datatypes into Corda will improve user experience and smoother v2->v3 upgrading process.

**Comment by lolo8304** [comment]
I will work on this @joeldudleyr3 
@ivanr3 - which version of corda do you actually use now? because in MASTER branch BigInteger serialization is implemented?

**Comment by lolo8304** [comment]
the 2 classes are already implemented for serialization and deserialization
see units-tests
- net/corda/serialization/internal/amqp/SerializationOutputTests.kt (incl BigInteger)
- net.corda.serialization.internal.amqp.OptionalSerializationTests

in current master many classes are implemented by default. Still I will update the code due to a copy / paste error in the description

**Comment by joeldudleyr3** [comment]
Fixed, thank you.
