### ISSUE TITLE
Custom CorDapps not loading properly into the Demobench

### ISSUE THREAD

**Issue by cribeiro23** [corda/corda#3702]
I'm trying to use my CorDapp with the Demobench, so I built the jar file using gradlew jar then loaded the jar into the demobench, However, when I launch some nodes, even though my app shows in the list of "Loaded CorDapps", the shell does not recognize my flows and I can't really do anything. My flows do not appear when I run "flow list". I can use my app using "runnodes.bat" so I think the issue is with the Demobench.

I am using version 3.1.

**Comment by joeldudleyr3** [comment]
Thanks for reporting. I've raised an issue on our internal JIRA here: https://r3-cev.atlassian.net/browse/CORDA-1852.

**Comment by cribeiro23** [comment]
Might be worth noting that this does not happen with all apps... the ObligationCorDapp, for example, seems to load properly

**Comment by joeldudleyr3** [comment]
@cribeiro23 Do you have an example of a CorDapp that doesn't load?

**Comment by cribeiro23** [comment]
Yeah, I can share my CorDapp with you through slack, but this one https://github.com/corda/negotiation-cordapp is also not loading properly (like I said it shows up as loaded but flows are not recognized)

**Comment by pinkjersey** [comment]
I also have this issue. My cordapp runs OK when I use runnodes, but not through demobench. Version 3.2. In the demobench logs I see the cordapp loader loading my cordapp but I assume it's not finding any flows, for whatever reason. Do flows need to be annotated a special way?

**Comment by pinkjersey** [comment]
Replication steps:
1) clone the latest version of cordapp-template-kotlin as foo
2) `gradlew.bat jar` creates foo-0.1.jar which, when unzipped shows that it does not contain the template
3) `gradlew.bar deployNodes` creates a bunch of directories in build\nodes. If you look in the cordapps dir, you will find two jars: one the blank foo jar, and second a jar named cordapp which contains the template classes.

The bug is that a) foo jar contains nothing and b) a jar named cordapp is created. My gut feeling is that a build.gradle file somewhere is missing a : before cordapp.

**Comment by mikehearn** [comment]
Thanks for the extra info, this will help a lot.

**Comment by DomSteil** [comment]
Same issue here, running flow list and the default flows are the only ones listed.

**Comment by RimashMohomed** [comment]
I have the same issue, when deploying through Dockerform. version 4.1

**Comment by yvesR3** [comment]
FYI, I've had the same issue, before going through this entire process (and IF you wrote your own custom Cordapp) check that the tests for it are passing as well. Because if the flow tests or contract tests don't pass, the same thing will happen (flows not showing up when 'flow list' is used on command line).

**Comment by rick-r3** [comment]
DemoBench is deprecated
