### ISSUE TITLE
Large messages not working

### ISSUE THREAD

**Issue by Quiark** [corda/corda#412]
Hi,

on corda M9.1. We tried to upload and open attachments larger than 100 kB and ran into problems. This is what I found:

* the RPC client just hangs waiting for response but never gets it because the node errors out
* the error is in `RPCDispatcher.getUser()`, large messages are missing the `_AMQ_VALIDATED_USER` property
* in some cases (such as increasing large message size in RPC client), a node will complain message is not authenticated

**Comment by mikehearn** [comment]
Assigning to Kostas. @exFalso wrote the support for sending streams over RPC.

This is almost certainly related to the hack that's in there to break messages up into chunks. 100kb is the chunk size. If it is, rather than fix the hack, I'd like us to just start using Artemis/MQ properly ... it does allow you to directly connect streams to messages and then the framework takes care of the chunking for us, it will avoid issues like this and avoid the file ever having to be entirely in memory at once. There's really no reason for us to do chunking at the app layer.

**Comment by kchalkias** [comment]
@mike it seems that Artemis/MQ supports compression, should we try that as well for big files?

**Comment by exFalso** [comment]
This is related to Artemis's large message handling, we've debugged this a bit before submitting #281. The stream functionality is independent, the bug can be reproduced by simply sending a large message

**Comment by mikehearn** [comment]
Right, makes sense:

http://activemq.apache.org/artemis/docs/1.5.0/large-messages.html

> Any message larger than a certain size is considered a large message. Large messages will be split up and sent in fragments. This is determined by the parameter minLargeMessageSize.  The default value is 100KiB.

**Comment by kchalkias** [comment]
This [PR #452 ](https://github.com/corda/corda/pull/452) allows for 10MB attachments, but it didn't solve the large message issue yet.

**Comment by mikehearn** [comment]
Current status - this was blocked by an Artemis bug, which we have fixed upstream: https://github.com/apache/activemq-artemis/commit/06dab31fd0c139d662a3a5973b9a06fe711e0faf

We waited for a new Artemis (2.4.0) which includes the fix and have upgraded ourselves to use it. So this should now work. @cburlinchon has been working on finishing up the loose ends on our end and making sure there are tests of it.
