### ISSUE TITLE
Enhancement: MetaParty or Nodeless Party

### ISSUE THREAD

**Issue by nimmaj** [corda/corda#4502]
We have a declarative need to be able to have states that:

 * are stored on a group of parties (ie routing)
 * have some rules about signing by the parties (ie signing)

One way of describing this is that it would be awesome if we could have a Party that is composed of Parties (ie composite pattern).  Richard often describes this as a nodules party.

Our specific use case relates to one of our DigitalMutuals being able to issue a Token.  We would like the issuer to be the mutual itself, not one specific Party in that mutual.  We would also like, say, m of n of the members of the mutual to have to sign a transaction that spends some of the states belonging to the mutual.

There are some obvious issues here, e.g. membership of the mutual changing over time.  And there are perhaps ways that we could approach this by managing all this explicitly and maybe using encumberances.

## Thought Experiment

In Corda 4, Roger is adding accounts, tokens and keys for accounts.  If we start to tease apart routing and signing, it starts to feel like a composite party might be quite an interesting concept.  In this case an account could correspond to a Party.  Routing wise, it would map to a single node.  Signing wise, to its key.   

We could have a Party that was a group of Parties.  In this case perhaps the states route to all the parties (strategy?) and the signing aspects are handled by a composite key (but other strategies could also be used). 

The existing Corda 3 model is trivial in this case.  

This is just one way of solving the underlying requirement.  Hopefully this issue can be a place to discuss ways of solving this problem.  Look forward to hearing your views :-)

**Comment by mikehearn** [comment]
We already have `CompositeKey` which is basically that. There's no notion of a labelled identity for a composite key, but I'm not sure it's necessary for the signing part. Unfortunately `CompositeKey` isn't fully supported by every part of the API - as you can imagine, the notion of composite identities has quite deep impact almost everywhere. For example the vault doesn't really know what to do with these - it's fairly meaningless to pick up a token controlled by a composite key during coin selection because you wouldn't know how to get the other parties to sign (or even who they are, necessarily).

For the routing/data distribution part, I suppose that's what the proposed "clubs" feature would do, but we don't have anything like that yet.

I think over time we'll continue to chip away at this, but as a relatively low priority, so this is a good place for contributions! I'd start by working on composite keys, and in particular, fleshing out a set of APIs that make them easy to work with. Some obvious places where we need beefing up:

* An app that shows how to verify satisfaction of a `CompositeKey` by a `Command` in contract logic (something like `require(ckey.isFulfilledBy(command.signers))`)
* Upgrades to `CollectSignaturesFlow` and/or `AbstractStateReplacementFlow` to try to gather a threshold of signatures over the transaction. This would require some upgrades to the flow framework because now, for the first time, we have the notion of _trying_ to involve a participant but needing to move forward if they don't reply in time, or opt not to take part. So we need to flesh out support for timeouts, parallel sub-flows and so on. Some of this work is already on the radar of @shamsasari and his team because they need to do some of this as part of making the existing system more robust.
* The right design here needs a bit of thought - do we need a generic `GatherParticipantsFlow` that does a kind of two-phase process whereby all possible parties are contacted and asked if they wish to proceed ... perhaps given an invalid template transaction ... along with a timeout, and the ones that reply in time are then sent the final tx for signing. Presumably inside a while loop to handle the case where a participant that signalled agreement dropped out between agreeing and signing. And if so, would `GatherParticipantsFlow` tackle invoking the subflow with the selected list of participants ... probably yes? There's probably a need for a notion of flow factories in here too.
* `AbstractStateReplacementFlow` needs to be upgraded to use `CollectSignaturesFlow`.

**Comment by joeldudleyr3** [comment]
@mikehearn I believe we also need to improve the vault's `isRelevant` logic to store states which are owned by a `CompositeKey` for which you own one of the leaf keys.

**Comment by mikehearn** [comment]
Yes, although that may itself not be the right way to do things - what does it mean to have a state you don't fully control in your vault? The whole vault/wallet analogy is already slightly dubious and starts to break down completely when you have group or threshold controlled states. They aren't necessarily available for use and aren't assets you can spend at will, so maybe what we need is to split the concept of a vault into pieces? 

What we really need here is some deep thinking about use cases and what the ideal sort of API for that use case looks like. Maybe if all the keys in a composite key are employees of the same org, for instance, the vault API and analogy still holds, but if they're different then it doesn't.

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4245](https://r3-cev.atlassian.net/browse/CORDA-4245)
