### ISSUE TITLE
If a node has already recorded a transaction, they cannot re-record it as an observer

### ISSUE THREAD

**Issue by joeldudleyr3** [corda/corda#4523]
In `ServiceHubInternal.recordTransactions`, any transactions that have already been recorded by the node are discarded:

    val recordedTransactions = txs.filter { validatedTransactions.addTransaction(it) }

This is an issue if you have already seen a transaction, but now want to re-record it as an observer using the Observable States feature.

**Comment by mikehearn** [comment]
You can't do that. The docs state clearly that a node (and therefore identity) can either be an observer *or* a participant, but you can't be both. If you want a node to see transactions but not necessarily be involved, you can just add them as a participant, and this issue goes away.

What we probably need to do here is deprecate the current observer node functionality and take it through the design process properly, so we have established patterns for this. The current observer node feature was a mistake caused by giving in to a false deadline (another mistake).

**Comment by viraj124** [comment]
Hi Mike the thing you said regarding Making the observer node as a participant worked absolutely fine in corda 3.3 but in corda 4 since we define the sessions of all participants in the finality flow then how can we handle that as it requires a
