### ISSUE TITLE
Provide fault-tolerant examples with threshold  transaction signing

### ISSUE THREAD

**Issue by remmeier** [corda/corda#5143]
we have use cases that are time-sensitive and as such should be notarized as quickly as possible. in that regard a quorum of some companies would be sufficient for us to do transaction signing. So if any one company is unreachable, the transaction can continue with notarization and be then be sent to all parties (which may take any amount of time until their nodes are up and running again).

Similar questions have been asked on stackoverflow:

https://stackoverflow.com/questions/53867523/corda-flow-timeout
https://stackoverflow.com/questions/47700190/making-asynchronous-http-calls-from-flows/47701824#47701824

Ideally a solution does not make use of timeouts, but just proceeds as soon as the first k out of n signatures arrived. Maybe it would be worthwile to give developers a more low-level API next to quasar, like based on https://projectreactor.io/ where such things can be implemented quite well.

**Comment by mikehearn** [comment]
I've filed https://r3-cev.atlassian.net/browse/CORDA-2966

There are two feature requests here:

1. Ability to fork/join on flows, with join semantics something like the win32 [WaitForMultipleObjectsEx API](https://docs.microsoft.com/en-us/windows/desktop/api/synchapi/nf-synchapi-waitformultipleobjectsex)
2. Alternative/lower level API for managing communications.

Adding (1) would be a great subject for a contribution. There are [docs on how the state machine manager works](https://docs.corda.net/contributing-flow-state-machines.html), and this would be a case of adding a new suspending API. However, it does requires some careful thought, which we could do on this issue or on corda-dev where there may be a wider audience.

The main reasons it requires careful thought are as follows:

* At the moment, Corda is designed on the assumptions that nodes are alive most of the time. So if outages are rare, maybe in the short term (i.e. what to do next) it's sufficient to just add send/receive timeouts and maintain the single-threaded nature of control flow, which simplifies things for developers dramatically. You say you need to be able to proceed if nodes are down - do you anticipate this being a frequent occurrence and if so, how come? Are you imagining nodes not run by IT professionals, for example? Nodes that are frequently offline open up a bunch of other issues too that'd need to be tackled as a group.
* The flow framework is partly about creating ambient app-level security through context. If you have a step in your protocol where you sign a transaction, it helps a lot if the only way to reach that step is by passing through other steps first like business network membership checks, human approvals, database lookups, negotiations and so on. If you can skip forward in a flow then it suddenly becomes way harder to make your app secure. "Skipping forward" isn't supported but when app developers break up their flows into pieces, the same effect can be seen. So now if we're asking several parties to sign a transaction, but _in parallel_, there's a question of how they were brought up to speed on what's going on. Presumably you need the ability to run entire subflows in parallel and join on those, rather than do a scatter/gather sendAndReceive. And so what happens if some parties were already up to date because of prior flow actions, and others were not - some of those subflows need to be inlined and others need to be top level. This needs careful treatment to avoid breaking things.

The good news is this is already very high up our priority list for other reasons - we want to be able to split into parallel paths for sending finalised transactions to peers in FinalityFlow but the same issue arises: _probably_ those nodes aren't going to accept just random transactions submitted by anyone, there's going to be at least some sort of conversation leading up to that point, and if the node is down you won't even reach that point either. So how we integrate this notion of "complex conversations in which parts proceed at different speeds to other parts" does require thought.

For (2) I think simply dropping in an observables framework wouldn't help. We already use RxJava of course which is very similar to Project Reactor. Observable stream frameworks aren't designed to manage state machines, they're pretty different tasks. Note that Quasar *does* have APIs that are of a similar bent already, see the section "Sending and Receiving Messages, ActorRef" in [the documentation for Quasar Actors](http://docs.paralleluniverse.co/quasar/) but they aren't so useful to us because we want the ability for everything to persist across restarts and failovers, which means we need to be able to persist at all times what a flow is waiting for in the database. Most actor/stream frameworks are designed to be in-memory only. The work involved here isn't actually working around or adding things to Quasar, that's a red herring. The work is integration with the state machine manager to ensure what the flow is waiting for is persisted, and when messages arrive or timeouts expire the flows are re-awakened and resumed.

**Comment by remmeier** [comment]
> You say you need to be able to proceed if nodes are down - do you anticipate this
> being a frequent occurrence and if so, how come? Are you imagining nodes not 
> run by IT professionals, for example? 

there are two areas where it would be interesting to us (also slightly related):

1. in our case there are use cases on the horizon where a large number of small companies would join the network. Not yet clear whether they would share a Corda node with some multi-tenancy capability or really have a node on their own. We are not overly fond of the former idea in terms of privacy, so we investigate whether to follow up with the later. Seems like the avenue to go in general. Unlike our regular deployment, we probably would keep those small and light. And what infrastructure they would run is not clear. So we would have a large number of nodes, not too much control over everything and more than likely not everything as reliable as we would desire. It could also provide a stepping stone for other use cases at even smaller scales (single persons, sensors, objects).

2. we work around car objects in one of our systems. The data model is split into two parts. More private states between few parties and a more public states shared between all nodes having a stake in that car.
For the later part we have the groups you mentioned (" other issues too that'd need to be tackled as a group"). "skipping forward" and "bringing nodes up to speed" are things that come up in this area. Currently not because we skipped them for being to slow, but for not considering them in the first place to participate in the transaction for reliablity reasons of the system when involving too many parties. In that regard the flexiblity/fault-tolerance of this ticket would help making the public part more responsive and robust without having  complexity. The data structures we use for states allow use to bring nodes up-to-speed quite easily (together with all the nice properties of Corda :-) )

**Comment by dazraf** [comment]
Can we revive this thread please. 
We've now seen in production on multiple occasions, where flows are left hanging owning to network issues with certain participants. Worryingly, even when those participants return, the flows remain unresolved. I should also add that these are not all signing flows. We have several use-cases where the flows use stages to negotiate the terms of the final transaction - we see the hanging flow issues during these handshake stages as well. 

From a general distributed systems perspective, I've often found that a timeout facility at an accessible point in the stack is very valuable. Can we consider a `timeout` parameter for `FlowSession#send`?
