### ISSUE TITLE
cannot enforce unicity

### ISSUE THREAD

**Issue by FredericHeem** [corda/corda#5222]
Is there a way to support composite primary key ? The aim is to make sure uniqueness of some state.
In JPA, there are 2 ways to implement them, with *@IdClass/@Id* OR with *@Embeddable/@EmbeddableId*
Unfortunately, none of them work within corda.
* *@IdClass/@Id*
Since the user defined state inherits from *PersistentState* and this class already uses *@Embeddable*, the *@IdClass*  implementation fails with the exception `expecting IdClass mapping`

* *@Embeddable/@EmbeddableId*
Please have a look at https://github.com/FredericHeem/fuzz-poker/blob/composite-pkey/cordapp-example/contracts-kotlin/src/main/kotlin/com/example/schema/PositionSchema.kt#L13 for a code sample 
The exception in this case is: 
```
Could not create Hibernate configuration: net.corda.core.schemas.PersistentStateRef must not have @Id properties when used as an @EmbeddedId: com.example.schema.PositionSchemaV1$PersistentPositionState.stateRef
net.corda.nodeapi.internal.persistence.HibernateConfigException: Could not create Hibernate configuration: net.corda.core.schemas.PersistentStateRef must not have @Id properties when used as an @EmbeddedId: com.example.schema.PositionSchemaV1$PersistentPositionState.stateRef
	at net.corda.nodeapi.internal.persistence.CordaPersistence$hibernateConfig$2$1.invoke(CordaPersistence.kt:111)

```

**Comment by FredericHeem** [comment]
Unicity can be achieved with *LinearState*

**Comment by FredericHeem** [comment]
Actually, unicity cannot be achieved with LinearState

Here are the steps to reproduce the error:
```
$ git clone git@github.com:FredericHeem/fuzz-poker.git samples -b checkForInputsAndReferencesOverlap
$ cd samples/cordapp-example
$ ./gradlew build
```
See the [test case here](https://github.com/FredericHeem/fuzz-poker/blob/checkForInputsAndReferencesOverlap/cordapp-example/workflows-kotlin/src/test/kotlin/com/example/test/flow/PositionFlowTests.kt#L58)

**Comment by mattbradburyuk** [comment]
Hi Frederic, 

I think in the Test Corda is behaving as I would expect. 

From a corda perspective, the two positions created in the `create twice` test are different because they come from different transactions. The uniqueness of the State in corda is dictated by its StateRef, which is a combination of the hash of the transaction which created the state and the index of the output state. 

Hence when you query the vault you get 2 different states back, even though you set them up to look exactly the same. 

I believe we have a workshop with you guys on Thursday 28th Nov, we can talk about ways to guarantee that the same position isn't generated twice in the workshop

**Comment by mattbradburyuk** [comment]
Note to self:
- Issuer maintains uniqueness of Position, by querying vault
- Only issuer can issue, which generates a random, high entropy UUID
- When State evolves, Contract logic requires continuity of linear id from previous state
