### ISSUE TITLE
Objects need marking with DeserialiseAsKotlinObjectDef

### ISSUE THREAD

**Issue by roger3cev** [corda/corda#527]
E.g. NullPublicKey

**Comment by rick-r3** [comment]
Given recent customisation we did to Kryo, I think we might be able to detect things like the fact it is a kotlin object rather than relying on the tag interface which we have to remember to add, assuming it's possible, since we intercept some of this logic for whitelisting checks and could pretend we'd seen a registration for any kotlin object definition for the associated special serializer we use when they implement this class.

**Comment by mikehearn** [comment]
That would be convenient. Kotlin puts some metadata in annotations.

**Comment by shamsasari** [comment]
#961 removed the need for DeserialiseAsKotlinObjectDef and was subsequently removed in #987.
