### ISSUE TITLE
Corda State Unique Constraints

### ISSUE THREAD

**Issue by MrMatthewLayton** [corda/corda#5393]
There is only one mechanism which can be applied to a Corda state in order to ensure uniqueness which is the `LinearState`. This provides the state with a pseudo-randomly generated, 128 bit, universally unique identifier (UUID) - similar to a primary key in a SQL database.

## Problem

Sometimes it makes sense for states to be uniquely constrained on other properties, or composites thereof but unlike a SQL database, there is no mechanism by which Corda states can be uniquely constrained on properties other than the linear ID.

## Example

The following example illustrates a simple state that models a friendship between two participants on the network - akin to friendships on Facebook.

```kotlin
data class Friendship(
    override val linearId: UniqueIdentifier,
    val partyA: AbstractParty,
    val partyB: AbstractParty
) : LinearState { ... }
```

The problem here is that I can issue the same friendship twice, just using two different linear IDs...

```kotlin
val initialFriendship = Friendship(UniqueIdentifier(), alice, bob)
val duplicateFriendship1 = Friendship(UniqueIdentifier(), alice, bob)
val duplicateFriendship2 = Friendship(UniqueIdentifier(), bob, alice)
```

As far as Corda is concerned they are different _enough_, however from a business perspective, this wouldn't make sense as you can't be friends with the same person more than once. _Notice that in this case, I have deliberately added two duplicates, because the ordering of the participants means the same thing_.

Corda does allow us to implement `QueryableState` which allows states to be mapped to a database table, and this feels like a natural place where constraints should apply. With respect to the example above, we can apply the following constraints to our schema:

```kotlin
@Entity
@Table(name = "friendship_states")
@UniqueConstraint(columnNames = ["partyA", "partyB"])
class FriendshipEntity(

    ...

    @Column(name = "partyA", unique = true)
	val partyA: AbstractParty,
	
	@Column(name = "partyB", unique = true)
	val partyB: AbstractParty
) : PersistentState()
```

This works from the perspective of persisting mapped states (entities), however it still has no impact on the states themselves, the reason being is that persistence of the entity is performed only after the signed transaction has been committed to the vault.

This causes two problems:

1. The ledger and the entity table are not synchronised.
2. It causes the node to fail as a result.

## Solution

One solution to this would be to check whether any of the states in the transaction implement `QueryableState` and persist the mapped entities before committing the signed transaction to the vault, thus  constituting a single successful (or unsuccessful) transaction, rather than a successful transaction to commit the signed transaction and a potentially unsuccessful transaction to persist the entity.

## Workaround

It's not the most elegant way to enforce this sort of rule at the state level, but the properties at the state level could be hashed together to form a 128 bit hash, which could then by applied to the linear ID...

```kotlin
val initialFriendship(UniqueIdentifier(id = uuid(hash128(sort(alice, bob)))), alice, bob)

val duplicateFriendship1(UniqueIdentifier(id = uuid(hash128(sort(alice, bob)))), alice, bob)
// ^ Should fail because it has a duplicate linear ID

val duplicateFriendship2(UniqueIdentifier(id = uuid(hash128(sort(bob, alice)))), alice, bob)
// ^ Should fail because it has a duplicate linear ID (alice and bob sort to the same order)
```

Again, not the nicest solution, but I can't see any other way to force constraints at the moment.

**Comment by woutslakhorst** [comment]
We have the same requirement for storing unique patient consent. The uniqueness is to make sure the vault doesn't become a mess with lots of duplicates. You may look at it as a git branch, there can be only 1 master.

At first I thought the `PersistentState` was going to save us, but after reading this issue, I tried some other stuff. I found a workaround which uses the database reference from the `serviceHub` to start a transaction before the `FinalityFlow` is called. With an active transaction in place the `jdbcSession` on `serviceHub` can be used to perform SQL queries.

Since the vault queries and custom queries are called within the same transaction, nothing will be stored in the Vault when the unique constraint is hit.

The same has to be done at the other nodes, if something goes wrong there an exception is raised which will be seen by the initiating node as an `UnexpectedFlowEndException`

### The initiating flow
```kotlin
@InitiatingFlow
@StartableByRPC
class UniqueStateFlow(val uniqId:UniqueIdentifier) : FlowLogic<SignedTransaction>() {

    @Suspendable
    override fun call(): SignedTransaction {
        // Obtain a reference to the notary we want to use.
        val notary = serviceHub.networkMapCache.notaryIdentities[0]

        // identity of this node
        val me = serviceHub.myInfo.legalIdentities.first()

        val newState = UniqueState(uniqId)

        val txCommand = Command(...)
        val txBuilder = TransactionBuilder(notary)
                .addOutputState(newState, UniqState.CONTRACT_ID)
                .addCommand(txCommand)

        // Verify that the transaction is valid.
        txBuilder.verify(serviceHub)
        val partSignedTx = serviceHub.signInitialTransaction(txBuilder)

        var otherPartySessions = (currentState.participants - me).map { initiateFlow(it) }

        // if the counterFlow raises, an exception will be thrown on the line below
        val fullySignedTx = subFlow(CollectSignaturesFlow(partSignedTx, otherPartySessions, GATHERING_SIGS.childProgressTracker()))

        store(uniqId.externalId!!)

        progressTracker.currentStep = FINALISING_TRANSACTION
        return subFlow(FinalityFlow(fullySignedTx, otherPartySessions, FINALISING_TRANSACTION.childProgressTracker()))
        }

    // run from a private method otherwise all kinds of classes will be serialised
    private fun store(externalId: String) {
        // this is the HACK
        val transaction = (serviceHub as AbstractNode<*>.ServiceHubInternalImpl).database.currentOrNew(TransactionIsolationLevel.READ_COMMITTED)
        val st = serviceHub.jdbcSession().prepareStatement("INSERT INTO consent_states VALUES(?)")
        st.setString(1, externalId)
        st.execute()
    }
}
```

### The counter flow
```kotlin
@InitiatedBy(UniqueStateFlow::class)
class AcceptUniqueStateFlow(val askingPartySession: FlowSession) : FlowLogic<SignedTransaction>() {
    @Suspendable
    override fun call(): SignedTransaction {
        val signTransactionFlow = object : SignTransactionFlow(askingPartySession) {
            override fun checkTransaction(stx: SignedTransaction) = requireThat {
                val output = stx.tx.outputs.single().data
                "This must be a UniqState transaction." using (output is UniqState)

                val st = output as UniqState
                store((st as ConsentState).uniqId.externalId!!)
            }
        }
        val txId = subFlow(signTransactionFlow).id

        return subFlow(ReceiveFinalityFlow(askingPartySession, expectedTxId = txId))
    }

    private fun store(externalId: String) {
        // HACK part 2
        val transaction = (serviceHub as AbstractNode<*>.ServiceHubInternalImpl).database.currentOrNew(TransactionIsolationLevel.READ_COMMITTED)
        val st = serviceHub.jdbcSession().prepareStatement("INSERT INTO consent_states VALUES(?)")
        st.setString(1, externalId)
        st.execute()
    }
}
```

Tests seem to work. I still have to validate what happens to the errored flows, we don't want to leave a huge mess in the flow hospital.

**Comment by series0ne** [comment]
@woutslakhorst We do something similar to this, whereby we just perform a vault query by linear ID before a transaction is even generated. If the vault query finds a dupe, it throws a `FlowException`.

The thing I don't like about this approach is that it's manual and can be circumvented by nodes using the same contract but different flows that don't check for unique constraints - ultimately it becomes something that developers have to think about...and they wouldn't have to with a traditional RDBMS.

For me, having data constraints applied to the schema, and have the schema persistence as a mandatory step of the transaction is **massively** beneficial and useful. Since the schema is part of the contract, it _could_ be argued that all participants have to verify the contract logic, and schema constraints in order for a transaction to commit in full - either it all happens or none of it happens.

**Comment by woutslakhorst** [comment]
I'm trying to figure out a different approach. The type of data we try to distribute has an 'owning' or 'originating' side (the party legally responsible for not leaking it).

Because the uniqueness problem mainly exists at the creation of the lineair state (race conditions), we let the 'owning' side create a 'genesis' record. A state without any contents, no other nodes or notary involved. In the flow a unique db record, as in my previous comment, is created within the same transaction as the vault. This flow will be the only flow that can create a state without consuming any previous states.

All other flows that can add, update or remove data must consume a previous state.

The only downside would be that other nodes can't create records, only update. To have other nodes initiate a new record, they probably have to use an old fashion REST API or something.

**Comment by MrMatthewLayton** [comment]
So, it turns out that my workaround (above) of hashing together certain state elements into a key and using this as the linear ID doesn't work. Corda doesn't enforce any constraint on there being only one unconsumed linear ID in the fault with a specific linear ID 😖

**Comment by MrMatthewLayton** [comment]
Just making a mental note... presumably unique constraints can also be circumvented by malicious nodes just modifying their database structure, and removing unique constraints from the table?

**Comment by woutslakhorst** [comment]
Noticed this too, currently we added a PersistentState with a version number which increases every time a state is consumed/produced. Together with a compound unique key, this solves it for now.

**Comment by MrMatthewLayton** [comment]
@woutslakhorst I think you and I have virtually reached the same solution. In my case, I've added a `previousStateRef` to the state. The contract states (pardon the pun) that on issuance, it must be null, and on amendment, it must point to the previous version of the state which is consumed in the same transaction. You could think of the `previousStateRef` as being akin to your version number, except I'd argue it's more relevant as you can enforce evolution constraints through your contract, and allows you to lean on the notary with regards to double spends.

**Comment by woutslakhorst** [comment]
@series0ne we use the stateRef from the transaction to do that. It allows for a list of previous references including different state types. Maybe this approach can be adopted in an example of best-practises or so? (if anyone from Corda reads this anyways)

**Comment by adagys** [comment]
Realise it's an old thread, but could you guys elaborate on how your solutions prevent duplicate issuances of the genesis states?

**Comment by woutslakhorst** [comment]
@adagys only 1 party is involved with generating the genesis state. Since only 1 party is involved, an unique constraint (annotated in the PersistantState) is now an option. When the party tries to insert a duplicate record the Flow will raise an exception when the final state would be written to the DB (FinalityFlow). Since 1 party is involved, no notary is involved as well.

**Comment by adagys** [comment]
Ah, got it. So you rely on schema constraints. During FinalityFlow the transaction will get recorded, but when updating the vault tables the uniqueness constraint violation will end up rolling back the db transaction and killing the flow.
Thanks

**Comment by nargas-ritu** [comment]
Internal ticket - [CORDA-4211](https://r3-cev.atlassian.net/browse/CORDA-4211)
