### ISSUE TITLE
Cordapp config should resolve references to environment variables.

### ISSUE THREAD

**Issue by zczapran** [corda/corda#5443]
https://github.com/corda/corda/blob/e35c0c1df74e9c475afc31ec7750b11c88bc4742/node/src/main/kotlin/net/corda/node/internal/cordapp/CordappConfigFileProvider.kt#L25

This line could be changed to:
```
ConfigFactory.parseFile(configFile.toFile())
```

This way references to environment variables could be resolved. Example config file:
```
secret_password = ${SECRET_PASSWORD_ENV_VAR}
```

Currently, when trying to read the variable (`services.getAppContext().config.getString("secret_password")`) an exception is thrown.

Usage of environment variable substitution is already implemented for the Node configuration (https://docs.corda.net/corda-configuration-file.html).

**Comment by davidrapacchiale** [comment]
Thanks @zczapran . We have opened a bug in our OS Jira instance to track this issue https://r3-cev.atlassian.net/browse/CORDA-3548. I will close this for now

**Comment by diegomrsantos** [comment]
Actually the change should be ` ConfigFactory.parseFile(configFile.toFile()).resolve()`. Is there any update about this issue?

**Comment by mnesbit** [comment]
I don't think we ever considered allowing CorDapp config to take environment variables, because you can't guarantee that all nodes encountering a CorDapp have that available. I had thought this might be talking about node config where we also had problems with blanket substitution and had to restrict substitutions to environment variables starting with CORDA_ or corda_ and the variables in the conf file are listed without the prefix e.g. CORDA_MY_PASSWORD gets substituted into ${MY_PASSWORD}. We will have to have a think about what is appropriate here,

**Comment by zczapran** [comment]
Let's say someone tries to build an Oracle service that will need to authenticate with an external system. What would be the right way to pass the authentication details to that Oracle service?
