### ISSUE TITLE
Revert Commit 1a7279c87d4 - CORDA-3167: Delete files from master 

### ISSUE THREAD

**Issue by opticyclic** [corda/corda#5444]
What are you trying to do with this commit:

https://github.com/corda/corda/commit/1a7279c87d44ed68259de347a1dde01fa05b81f3

https://r3-cev.atlassian.net/browse/CORDA-3167

> Description
> 
> Delete all files on master and and add a README explaining that this is not the branch one might be looking for (possibly including a hint where to find the actual code)

Have you just made up a new branching strategy instead of using any of the well established strategies??

Adding a commit that deletes the contents of master is going to cause problems.

**Comment by opticyclic** [comment]
@mikehearn : Can you chime in on this surprising decision and explain this branching strategy and how all of the existing strategies are deficient for Corda?

**Comment by mikehearn** [comment]
@opticyclic I wasn't involved in this decision. I've assigned @blsemo who can provide some justifications.

**Comment by opticyclic** [comment]
There is an email on the groups list
https://groups.io/g/corda-dev/message/1115

Whilst back porting can be time consuming, forward porting leads to regressions as fixes are made in one branch and then the client moves to the latest version and the issue re-occurs because it has been missed in the forward port.

This regression can't happen in the back port model as by definition the issue is always fixed in the latest version first.

This model is also going to provide confusion to contributors as master is the default branch in git where you expect the latest code to be and it is now no longer obvious where to make pull requests to.

**Comment by bpaunescu** [comment]
Forward porting is done as immediately after a commit to a  release branch. Assuming a forward port is forgotten, it gets picked up by the next forward merge.

**Comment by opticyclic** [comment]
Regardless of how confident you are of forward merging working (the history of capital markets applications causing regressions using this strategy means it is not in your favour), it doesn't explain why you would delete the _content_ of master.

FYI: I can't find an established branching strategy that doesn't use the master branch.

**Comment by blsemo** [comment]
We have changed the versioning and release procedure and policy for Corda to make it easier to maintain and develop serveral version of Corda in parallel - see the announcement email [here](https://groups.io/g/corda-dev/topic/corda_release_versioning/33140462?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,33140462) and a blog post explaining it [here](https://medium.com/corda/corda-release-versioning-changes-6281b02348fc).
In order to align our source control structure with the versioning, we have decided to have versioned development branches rather than one master branch - the moment there is more than one unreleased version in the works, the meaning of a "master" branch becomes a lot more difficult and less helpful.
Hence we have removed all files from master (to make it clear that nothing will be happening here anymore) and left a note where the action is taking place now. 
Thank you for your concern for the integrity of the Corda repository, thus pointing out that our documentation/communication was lacking  - we have now added a better explanation to the readme file and the commit messages as they clearly were more confusing than helpful - but we won't bring back the master branch. 
We also have internal reporting set up to ensure that changes do get merged forward and do not regress in later versions.
I hope you understand that I'd prefer to not discuss the pros and cons of different branching strategies and forward merging vs back-porting in this forum - feel free to drop me an email at my r3.com address in my profile if you want to discuss further.
