### ISSUE TITLE
Allow spent outputs in Corda's data model

### ISSUE THREAD

**Issue by MrMatthewLayton** [corda/corda#5868]
I am raising this issue for discussion as something that was previously discussed with @mikehearn regarding an idea to have _spent_ outputs as part of Corda's transaction model.

Typically, Corda state transition chains involve creation (output), evolution (input and output) and consumption (input) of a state. The problem is that in some scenarios, state transition chains either lead to an unspent output at the end of the chain that cannot be spent due to restrictions in the contract logic, or incomplete state chains because the final state is consumed, and therefore does not represent the final action in the chain of events.

Let's take the obligations CorDapp as an example. With the obligations CorDapp you can issue obligations and settle them, either in part or in full. Whenever you settle an obligation, it consumes the previous version of the obligation state and creates a new one; that is, unless the final settlement settles the obligation in full, in which case, the obligation is spent, with no output recording the final settlement; for example:

_Legend for the following tx examples..._
`<` = Input
`>` = Output
`.` = Spent Output

```
TX 1
====
> Obligation(me, you, $100)

TX 2
====
< Obligation(me, you, $100)
< Cash(you, me, $25)
> Obligation(me, you, $75)

TX 3
====
< Obligation(me, you, $75)
< Cash(you, me, $75)
```

From a vault query perspective, this looks like `$100 >> $75` but it would be nicer to see a full settlement chain like `$100 >> $75 >> $0`. With the current implementation you would have to make an assumption that the final obligation was fully settled because there's no unconsumed output.

The problem gets worse when you introduce data which may be useful in audit trails, for example, let's add the settlement date:

```
TX 1
====
> Obligation(me, you, $100, null)

TX 2
====
< Obligation(me, you, $100, null)
< Cash(you, me, $25)
> Obligation(me, you, $75, 01/01/2020)

TX 3
====
< Obligation(me, you, $75, 01/01/2020)
< Cash(you, me, $75)
```

Now you can't see when the final settlement was made because there's no output recording it. You could modify the contract to require an unspent output at the end of the chain that records the final settlement:

```
TX 1
====
> Obligation(me, you, $100, null)

TX 2
====
< Obligation(me, you, $100, null)
< Cash(you, me, $25)
> Obligation(me, you, $75, 01/01/2020)

TX 3
====
< Obligation(me, you, $75, 01/01/2020)
< Cash(you, me, $75)
> Obligation(me, you, $0, 02/01/2020)
```

Ultimately this is what the whole problem boils down to. It seems unusual to have state chains with an unspent output at the end that you can't do anything with, and this has an impact on how vault queries for partially settled or fully settled obligations would be implemented.

Now, I fully appreciate that the idea of a "spent output" goes against the grain of the UTXO model, however (at face value) it solves the problem:

```
TX 1
====
> Obligation(me, you, $100, null)

TX 2
====
< Obligation(me, you, $100, null)
< Cash(you, me, $25)
> Obligation(me, you, $75, 01/01/2020)

TX 3
====
< Obligation(me, you, $75, 01/01/2020)
< Cash(you, me, $75)
. Obligation(me, you, $0, 02/01/2020)
```

Now you can see a full audit trail of the obligation, and there's no unspent output at the end of the state chain, therefore queries using `Vault.StateStatus.UNCONSUMED` would only return partially settled obligations.

**Comment by gendal** [comment]
Interesting... so if I'm understanding you correctly, is the idea that we would introduce a new type of state that can never be referenced as an input?  A "terminal state", if you like?  So it would appear in the vault (and appear in certain types of query) but it would be invalid to reference it in another transaction.

Leaving aside compatibility concerns, etc., for now, would there need to be any other constraints to make it work?  eg could you have more than one of these in a transaction? Would it work better/worse if they were the _only_ outputs? Would it ever be required/desirable to _reference_ (but not consume) them in other transactions?

Part of me thinks this is really cool... but I also wonder if it's one of those things that it would be hard to ever get round to doing because you can achieve something "close enough" with existing functionality. Not sure!

**Comment by MrMatthewLayton** [comment]
@gendal Yes, a "terminal state" sounds about right, and yes, it would not be possible to reference the state in another transaction _(although at a slight tangent, I'm still highly skeptical as to the rationale of not being able to reference consumed states, but that's another matter)_.

My thoughts were something like this:

```
val transaction = with(TransactionBuilder(notary)) {
    addInputState(someStateAndRef)
    addSpentOutputState(someState)
}
```

When the transaction becomes (iirc) a `LedgerTransaction`, then `someState` essentially becomes `StateAndRef(someState, txref)`. In this case, both the input state, and the output state need to be notarised and consumed, and the ledger needs to be updated with a new output, but also marking that output as consumed on the participant/observer nodes through finality.

I guess this would require a `minimumPlatformVersion` change as it's not going to be backwards compatible with previous Corda transaction versions.

**Comment by gendal** [comment]
Why does the notary need to be involved? If the 'terminal state' is only added to a vault if the transaction it was created in has been notarised, why should the notary care about it at all? Normal (albeit modified) transaction verification rules could be used to ensure such a thing is never referenced, no? I guess a heavy-handed implementation would be one where they simply don't appear in the indexed list of 'regular' outputs?

I was intrigued by this statement: "(although at a slight tangent, I'm still highly skeptical as to the rationale of not being able to reference consumed states, but that's another matter)"... the idea of reference states was to allow you to create transactions that could only be confirmed if the data _and_ the reference data upon which they depend are current... ie trying to drive up consistency and eliminate errors caused by using stale data.  If you could get a tx notarised that references a _consumed_ state, 1) why would you want to and 2) wouldn't that cause more problems than it solved? (Genuinely curious btw)

**Comment by MrMatthewLayton** [comment]
@gendal that last code snippet was probably a bad example because it included an input state, which would definitely require notarisation to prevent double spends, so...

```
val transaction = with(TransactionBuilder(notary)) {
    addSpentOutputState(someState)
}
```

This requires notarisation for the same reason as an input state. The `StateRef` generated for this state would need to be notarised and marked consumed immediately from this transaction to prevent it from being spent (and **not** doing so would likely incur security vulnerabilities from a notarisation perspective), but it's also an output in the sense that it creates a new state on the ledger. You could think of this as combining two transactions into one:

```
TX 1 (Settle in full)
====
< Obligation(me, you, $100, null)
< Cash(you, me, $100)
> Obligation(me, you, $0, 01/01/2020)

TX 2 (Consume fully settled obligation)
====
< Obligation(me, you, $0, 01/01/2020)
```

In the example above, the contract logic prevents overpaying an obligation, but TX 2 might include something like an _Exit_ command, which just consumes a fully settled obligation. The idea of spent outputs would allow this behaviour to be combined into a single transaction, thus reducing contract complexity, reducing network load, and alleviating the need for an additional transaction to be notarised and stored in the vault.

```
TX 1 (Settle in full)
====
< Obligation(me, you, $100, null)
< Cash(you, me, $100)
. Obligation(me, you, $0, 01/01/2020)
```

By spending the obligation's `StateRef` immediately, you get the same effect as the example above, but without needing to generate, sign and notarise an entire transaction, just to spend the final output.

**Comment by MrMatthewLayton** [comment]
> although at a slight tangent, I'm still highly skeptical as to the rationale of not being able to reference consumed states, but that's another matter

This is probably an appalling analogy, but here goes...

We can observe the evolution of modern man though the fossil record. Imagine we model this as a set of state transitions...

```
TX 1
====
> EvolutionState("Australopithecus")

TX 2
====
< EvolutionState("Australopithecus")
> EvolutionState("Homo Habilis")

TX 3
====
< EvolutionState("Homo Habilis")
> EvolutionState("Homo Erectus")

TX 4
====
< EvolutionState("Homo Erectus")
> EvolutionState("Homo Neanderthalensis")

TX 5
====
< EvolutionState("Homo Neanderthalensis")
> EvolutionState("Homo Sapiens")
```

Now, say for example I want to generate a transaction that asserts some hypothesis or fact about "Homo habilis", and in order to do so, I want to use that as a reference state _(adding `r` for reference states)_. Bear in mind, it's no longer current, but it happened and we want to assert something _because_ it happened...

```
TX 1
====
r EvolutionState("Homo Habilis")
> FactState("Homo Habilis was shorter that both it's ancestor and descendant")
```

Such a transaction could never finalise with Corda today, because I can't reference that state.

**Comment by gendal** [comment]
"The StateRef generated for this state would need to be notarised and marked consumed immediately from this transaction to prevent it from being spent "  << OK... so in your model this is more an optimisation rather than a 'new' type of state.  I was imagining it as a new type of component in the transaction that is simply unspendable by definition.  Whereas yours is effectively a regular output with a flag that tells the notary "please immediately mark me as spent".  I wonder if that would work well with non-validating notaries or not. Interesting nonetheless

**Comment by gendal** [comment]
"Such a transaction could never finalise with Corda today, because I can't reference that state." << If you don't care about its currentness, could you use attachments? ok - a bit more cumbersome and I don't know if we optimise the dedup between an attachment that happens to be a tx and the tx itself (almost certainly not since attachments are zips) but it would work in principle I guess?

**Comment by MrMatthewLayton** [comment]
@gendal 
> Whereas yours is effectively a regular output with a flag that tells the notary "please immediately mark me as spent".

Exactly. I would imagine we'd need some more community buy-in for something like this to get implemented, but worth investigating?

> If you don't care about its currentness, could you use attachments?

Yes you could, but it certainly would be more cumbersome. I feel like the "reference states **must** be current" rule enforced by Corda would have been better left to the developer on a per-implementation, opt-in basis, though perhaps that's a little short sighted of me.

Relaxing the restriction on reference states would have certainly fixed the `StaticPointer` bug in a more elegant way.

**Comment by gendal** [comment]
cc @roger3cev do you recall why we didn't offer this option when implementing reference states?  I assume it was because the design vision was "never rely on out of data reference data again!" But maybe there was something more?

@rick-r3 I guess as maintainer you're the one to capture these ideas as things the community would like to see? or is it one for @chrischabot ?

**Comment by roger-that-dev** [comment]
This has always bugged me when handling lifecycles of things which can be cancelled/annulled/redeemed/etc! It's a nice idea but it does add yet more complexity to the platform - something which we are trying to reduce.

Stream of thoughts... From a reference data/fact state perspective... How is this different to issuing a `ContractState` onto the ledger which can only be used as a `StaticPointer` and just writing a contract for it which doesn't permit any updates?
