### ISSUE TITLE
Suggestion: Add possibility to delete attachment content

### ISSUE THREAD

**Issue by foultre** [corda/corda#5938]
It might be useful to be able to delete attachments from a corda node. Wether it is for cleaning unused attachment file or to comply with GDPR requirements "right to be forgotten".

The `CordaRPCOPS` API would be added this new feature `deleteAttachmentContent(attachmentHash)`:

The attachment row and hash would stay but the blob content of the column `CONTENT` would be changed to null and there might need to add a `DELETED` boolean to `NODE_ATTACHMENTS` table.

**Comment by mattbradburyuk** [comment]
@joeldudleyr3

**Comment by mattbradburyuk** [comment]
I followed up with the Engineering team:
We can't delete attachments because it will potentially break the backchain verification. Resolve Transaction Flows trigger implicitly during Collect Signatures and Finality Flows, its very hard to guarantee that there will never be requests for the backchain. Hence we would not introduce this feature into the platform.

**Comment by foultre** [comment]
OK, thanks for letting me know.
