### ISSUE TITLE
Subsequent start-up of nodes in cordapp-template does not start web-server

### ISSUE THREAD

**Issue by jamescarlyle** [corda/corda#97]
Fresh repo clone of both corda and cordapp-template (both master), following the instructions in the developer docs.

1) gradlew deployNodes is successful
2) runnodes causes nodes to start successfully, including webserver.
3) node processes are terminated.
4) restart of nodes (either together with runnodes, or individually by 'build/nodes/nodea; java -jar corda.jar && exit') causes nodes to restart successfully, but the webserver is not started. There are no warning or error messages displayed.

<img width="934" alt="screen shot 2017-01-02 at 09 51 03" src="https://cloud.githubusercontent.com/assets/2500678/21591257/7a6f75da-d0d0-11e6-8c7d-f9e6ab43e190.png">

The log file produced during startup (which contains the node configuration) is attached.
[node-Jamess-MacBook.local.txt](https://github.com/corda/corda/files/680944/node-Jamess-MacBook.local.txt)

Note that gradlew clean, followed by gradlew deployNodes and then runnodes will cause the webserver to start normally.

**Comment by patrickkuo** [comment]
This is because "Controller" node is terminated, the Controller act as Network Map as well.
NodeA's webserver is not started because it is trying to connect to the network map, which will wait indefinitely until the network map node is online.

I will create a Jira to add logging when the node is waiting for network map.

**Comment by patrickkuo** [comment]
JIRA - https://r3-cev.atlassian.net/browse/CORDA-145

**Comment by patrickkuo** [comment]
Hi @jamescarlyle, looks like the problem you had was because the network map service(Controller) was down. I have made Corda node print out messages if its taking long time to connect to network map, so it doesn't appear to "hang" and give more insight of the node's status.

Can you please check if there are still problem starting up nodes? (please make sure Network Map node is up as well)

**Comment by patrickkuo** [comment]
I will close this issue for now, please reopen it if you see this issue happening again.
