### ISSUE TITLE
corda --version doesn't work if the node is already running

### ISSUE THREAD

**Issue by mikehearn** [corda/corda#970]
We do the is-already-running check before handling --help/--version so if your corda.jar is in the working directory and you run `./corda.jar --version` then it just prints out the PID and recommends you stop the other node first.

**Comment by ing-rafbhoedjang** [comment]
It seems that this also happens when you run ```./corda.jar --initial-registration```. The instructions for ansible at <https://r3-cev.atlassian.net/wiki/display/AWG/Corda+TestNet+Node+Configuration> suggest to cd into _/opt/corda_ and they state (section 9) that it is not necessary to stop the service. Now that I've reread the page: the non-ansible instruction say that the service should be stopped (section 6).

**Comment by mikehearn** [comment]
This is fixed now.
